### ISSUE TITLE
Debugging errors

### ISSUE THREAD

**Issue by joachimboggild** [craigbridges/Nettle#1]
Hi,

I think your library is very nice. I have a problem during debugging, though, which you might be able to help me with:

Example: I have made a function called "FormatDecimal", which takes a value of type decimal and formats it with a format string. But I use the function in many places in my template, and I get an error somewhere with the error message "The value '' is not valid for the parameter Number'. Is there a way that I can see which property is being processed?

Example: If I have a template with this code: 

```
<p>{{@FormatDecimal($.BuyPrice, "N2")}}</p>
<p>{{@FormatDecimal($.SellPrice, "N2")}}</p>

```
I would like a way to know if the error occurred during the processing of "BuyPrice" or "SellPrice".

Is this possible?

**Comment by joachimboggild** [comment]
I can see that you did some changes to fix this. Great stuff :-)

**Comment by davidatchangedigital** [comment]
Hi Joachim,

Thank you very much for your feedback. It's great to see that someone else is using Nettle!

As you have already seen, I've added more detail to the exception so now you can see the actual block of code that raised the error. I have also added the start and end position so you can find exactly where it is in your template.

I haven't released these changes on NuGet yet, but will do soon.

I hope this helps :)

**Comment by craigbridges** [comment]
Hi Joachim,

Thank you very much for your feedback. It's great to see that someone else is using Nettle!

As you have already seen, I've added more detail to the exception so now you can see the actual block of code that raised the error. I have also added the start and end position so you can find exactly where it is in your template.

I haven't released these changes on NuGet yet, but will do soon.

I hope this helps :)

**Comment by joachimboggild** [comment]
Hi Craig,

Sure, it is a great help. Thanks for fixing this! It is so much better to be using a template system like this instead of having to rely on .NET html builder classes, which are waay to obese...
